name: ciCdPipeline

on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkoutCode
        uses: actions/checkout@v2

      - name: setUpNodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: installDependencies
        run: npm install

      - name: runTests
        run: npm test

      - name: semanticRelease
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

